import React from 'react';
import { motion } from 'framer-motion';
import Button from '../shared/Button';
import Badge from '../shared/Badge';
import { IncidentReport } from '../../types';

interface ReportPreviewProps {
  report: Partial<IncidentReport>;
  onBack: () => void;
  onGenerate: () => void;
  generating: boolean;
}

const ReportPreview: React.FC<ReportPreviewProps> = ({ report, onBack, onGenerate, generating }) => {
  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-6"
    >
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-8">
        {/* Header */}
        <div className="border-b border-gray-700 pb-6 mb-6">
          <div className="flex items-start justify-between mb-4">
            <div>
              <h1 className="text-2xl font-bold text-white mb-2">{report.title}</h1>
              <p className="text-gray-400">Incident Report</p>
            </div>
            <Badge severity={report.severity || 'medium'}>
              {report.severity?.toUpperCase()}
            </Badge>
          </div>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-gray-400">Incident Type:</span>
              <span className="text-white ml-2">{report.incident_type}</span>
            </div>
            <div>
              <span className="text-gray-400">Detection Time:</span>
              <span className="text-white ml-2">
                {report.detection_time ? new Date(report.detection_time).toLocaleString() : 'N/A'}
              </span>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-white mb-3">Executive Summary</h2>
          <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
            <p className="text-gray-300 text-sm leading-relaxed">
              {report.executive_summary || 'Executive summary will be generated by AI...'}
            </p>
          </div>
        </div>

        {/* Description */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-white mb-3">Incident Description</h2>
          <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
            <p className="text-gray-300 text-sm leading-relaxed">{report.description}</p>
          </div>
        </div>

        {/* Affected Systems */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-white mb-3">Affected Systems</h2>
          <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
            <div className="flex flex-wrap gap-2">
              {report.affected_systems?.map((system, index) => (
                <span
                  key={index}
                  className="px-3 py-1 bg-red-500/20 text-red-400 text-sm rounded-full border border-red-500/30"
                >
                  {system}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Indicators of Compromise */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-white mb-3">Indicators of Compromise</h2>
          <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
            <div className="space-y-2">
              {report.indicators?.map((indicator, index) => (
                <div key={index} className="flex items-center gap-2 text-sm">
                  <svg className="w-4 h-4 text-orange-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                  <code className="text-gray-300 font-mono">{indicator}</code>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Attack Vector */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-white mb-3">Attack Vector</h2>
          <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
            <p className="text-gray-300 text-sm leading-relaxed">{report.attack_vector}</p>
          </div>
        </div>

        {/* Timeline */}
        {report.timeline && report.timeline.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-semibold text-white mb-3">Incident Timeline</h2>
            <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
              <div className="space-y-4">
                {report.timeline.map((event, index) => (
                  <div key={index} className="flex gap-4">
                    <div className="flex-shrink-0 w-24 text-sm text-gray-400">
                      {new Date(event.timestamp).toLocaleTimeString()}
                    </div>
                    <div className="flex-1">
                      <div className="font-medium text-white text-sm mb-1">{event.event}</div>
                      <div className="text-gray-400 text-sm">{event.description}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* MITRE ATT&CK */}
        {report.mitre_techniques && report.mitre_techniques.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-semibold text-white mb-3">MITRE ATT&CK Techniques</h2>
            <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {report.mitre_techniques.map((technique, index) => (
                  <div key={index} className="flex items-center gap-3 p-3 bg-gray-800 rounded-lg">
                    <span className="px-2 py-1 bg-blue-500/20 text-blue-400 text-xs font-mono rounded">
                      {technique.technique_id}
                    </span>
                    <span className="text-sm text-gray-300">{technique.tactic}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Mitigation Steps */}
        {report.mitigation_steps && report.mitigation_steps.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-semibold text-white mb-3">Mitigation Steps</h2>
            <div className="bg-gray-900 border border-gray-700 rounded-lg p-4">
              <ol className="space-y-3">
                {report.mitigation_steps.map((step, index) => (
                  <li key={index} className="flex gap-3">
                    <span className="flex-shrink-0 w-6 h-6 bg-green-500/20 text-green-400 rounded-full flex items-center justify-center text-sm font-medium">
                      {index + 1}
                    </span>
                    <span className="text-gray-300 text-sm">{step}</span>
                  </li>
                ))}
              </ol>
            </div>
          </div>
        )}
      </div>

      <div className="flex justify-between">
        <Button type="button" onClick={onBack} variant="outline" disabled={generating}>
          Back
        </Button>
        <Button 
          type="button" 
          onClick={onGenerate} 
          variant="primary"
          disabled={generating}
        >
          {generating ? (
            <>
              <svg className="animate-spin -ml-1 mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Generating...
            </>
          ) : (
            'Generate Report'
          )}
        </Button>
      </div>
    </motion.div>
  );
};

export default ReportPreview;

// Made with Bob
